spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
  main:
    allow-bean-definition-overriding: true

# SOAP client configuration (which SOAP server we want to access)
webservice.client:
  cloudUsername: "aleksandrkhalikov.fid@t1002"
  cloudPassword: "mQcgT2pGGtkALk43lmhf5p6LnSIbUrCLD4Q4Zk7Q"
  urlServiceDeployNew: https://odmeudemo1.bpm.ibmcloud.com/odm/dev/DecisionService/ws/serviceDeployNew/serviceOpp/v75

soap.messages:
  logging: true
  extract: true
endpoint.autoinit: false

# Url for getting SOAP Request
ServiceDeployNewGetRequestURL: https://odmeudemo1.bpm.ibmcloud.com/odm/dev/DecisionService/rest/v1/serviceDeployNew/serviceOpp/xml

cloudUrl: "https://odmeudemo1.bpm.ibmcloud.com/odm/dev/res"