<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ServiceOppDecisionService" targetNamespace="http://www.ibm.com/rules/decisionservice/ServiceDeployOld/ServiceOpp" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:dstns="http://www.ibm.com/rules/decisionservice/ServiceDeployOld/ServiceOpp" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"><xsd:import namespace="http://www.ibm.com/rules/decisionservice/ServiceDeployOld/ServiceOpp" schemaLocation="ServiceDeployOldServiceOppDecisionService.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="ServiceOppRequest">
    <wsdl:part name="ServiceOppRequest" element="dstns:ServiceOppRequest">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ServiceOppResponse">
    <wsdl:part name="ServiceOppResponse" element="dstns:ServiceOppResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ServiceOppSoapFault">
    <wsdl:part name="fault" element="dstns:ServiceOppException">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ServiceOppDecisionService">
    <wsdl:operation name="ServiceOpp">
      <wsdl:input name="ServiceOppRequest" message="dstns:ServiceOppRequest">
    </wsdl:input>
      <wsdl:output name="ServiceOppResponse" message="dstns:ServiceOppResponse">
    </wsdl:output>
      <wsdl:fault name="ServiceOppSoapFault" message="dstns:ServiceOppSoapFault">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServiceDeployOldServiceOppBinding" type="dstns:ServiceOppDecisionService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ServiceOpp">
      <soap:operation soapAction="ServiceOpp" style="document"/>
      <wsdl:input name="ServiceOppRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="ServiceOppResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ServiceOppSoapFault">
        <soap:fault name="ServiceOppSoapFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServiceOppDecisionService">
    <wsdl:port name="ServiceDeployOldServiceOppPort" binding="dstns:ServiceDeployOldServiceOppBinding">
      <soap:address location="https://odmeudemo1.bpm.ibmcloud.com/odm/dev/DecisionService/ws/serviceDeployOld/serviceOpp/v75"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
